### ISSUE TITLE
[BUG] Incorrect damage applied on bard melee attacks

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/13th-age#497]
## Describe the bug
Attacks made with math functions in them (such as the Bard's `max(@str.dmg, @dex.dmg)` ) are unable to retrieve the portion of the roll under the math formula when generating the amount to be applied by the context menu on inline rolls.

## Steps To Reproduce
1. Roll a basic melee attack using the bard class.
2. Attempt to apply damage.
3. The damage applied will exclude the ability modifier due to it being in a function.

## Expected behavior
The full damage should be applied.

## Recordings
https://github.com/user-attachments/assets/13be74ae-4076-4ad3-a05a-f5d43f63ac19

**Comment by LegoFed3** [comment]
I can't seem to be able to replicate this, whether on the bard or a custom power.
![immagine](https://github.com/user-attachments/assets/c48338f1-e7d8-4524-a76d-dcf72f648156)

The actual problem is that if you use the application menu from an *expanded* inline roll our code to extract the roll only catches the first die.
